Import upstream version 1.0.63
Signed-off-by: Chrysostomos Nanakos <cnanakos@openvstorage.com>

diff --git a/debian/tests/admin b/debian/tests/admin
--- a/debian/tests/admin
+++ b/debian/tests/admin
@@ -1,13 +1,14 @@
-#!/bin/bash
+#!/bin/sh
 #---------------
 # Testing tgtadm
 #---------------
-set -e
-ADMIN=tgtadm
-$ADMIN --help > /dev/null 2>&1
-RET=$?
 
-if [[ $RET != 0 ]]; then
-  echo "ERROR, ${ADMIN} is not running"
-  exit $RET
-fi
+for cmd in tgtadm tgt-admin tgtimg; do
+	/usr/sbin/$cmd --help > /dev/null 2>&1
+	RET=$?
+
+	if [ $RET -ne 0 ]; then
+	  echo "ERROR, failed to run ${cmd}" >&2
+	  exit $RET
+	fi
+done
